### ISSUE TITLE
Arrange Groups Request

### ISSUE THREAD

**Issue by rayman89** [denschub/firefox-tabgroups#45] opened 2016-09-04 08:26 UTC
Great add-on. I was wondering if you could make it possible to re-arrange the group order by dragging the group name or something (Ex: group 1 2 3 to 1 3 2).

**Comment by skyschub** [comment] 2016-09-04 19:44
Could you please open seperate issues? :)

**Comment by rayman89** [comment] 2016-09-04 21:12
Done

**Comment by skyschub** [comment] 2016-09-04 21:26
Actually, dupe of #18

**Closed as completed by skyschub** 2016-09-04 21:26 UTC
Labels: feature
