### ISSUE TITLE
Issue with groups when opening a new window

### ISSUE THREAD

**Issue by rayman89** [denschub/firefox-tabgroups#47] opened 2016-09-04 21:12 UTC
I noticed something that might be an Issue I'm not sure but when you open a new window; for that window all the groups are like they don't exist they only exist on the original window you had.

**Comment by skyschub** [comment] 2016-09-04 21:25
Actually a dupe of #5. Groups ae not exchangeable between windows for now.

**Closed as completed by skyschub** 2016-09-04 21:25 UTC
