### ISSUE TITLE
Panel is not displayed correctly and unusable (crushed)

### ISSUE THREAD

**Issue by etnbrd** [denschub/firefox-tabgroups#13] opened 2015-11-25 10:20 UTC
Linux Arch 4.2.5-1-ARCH x86_64 GNU/Linux
Firefox Nightly 45.0a1 (2015-11-14)

![screenshot from 2015-11-25 11-13-31](https://cloud.githubusercontent.com/assets/5691124/11394559/2ae4144c-9366-11e5-833a-a37ce9a34999.png)

**Comment by skyschub** [comment] 2015-11-26 09:15
Since I'm not able to reproduce this, I need some more information:
- Does this happen all the time or does it sometimes work after opening the panel again?
- Does it change it's appearance when you hover over the "invisible" elements?
- Could you please check the browser console (usually Ctrl-Shift-J) for any errors and post them here if any?

Thank you!

**Comment by etnbrd** [comment] 2015-11-26 09:20
The panel never displayed correctly.
I can scroll inside the crushed panel, see all the group tabs inside, and
click on the group tabs.
It works properly, except it is displayed improperly.
In the browser console, I get an error when I click on the icon :
TypeError: Property 'handleEvent' is not callable.

Thanks.

**Comment by skyschub** [comment] 2015-11-26 09:27
I see. I'm fairly confident that this is related to [Bug 1224974](https://bugzilla.mozilla.org/show_bug.cgi?id=1224974) which means 2015-11-25 would be a working build. Would you mind giving it a try?

Edit: Oh wait, I just realized that you can scroll _inside_ the panel. MIght I ask there the "TypeError: Property 'handleEvent' is not callable." error appears? There should be a file name and a line number on the right side. If it's truncated, mark the text and copy it and you'll have the full filename in your clipboard.

Also, I expect you're on the version published on AMO?

**Comment by etnbrd** [comment] 2015-11-26 10:33
Nope, the bug is still present wiith Firefox-nightly 45.0a1 (2015-11-25) :(

**Comment by skyschub** [comment] 2015-11-26 11:07
Please address my other questions as well:

> Edit: Oh wait, I just realized that you can scroll inside the panel. MIght I ask there the "TypeError: Property 'handleEvent' is not callable." error appears? There should be a file name and a line number on the right side. If it's truncated, mark the text and copy it and you'll have the full filename in your clipboard.
> 
> Also, I expect you're on the version published on AMO?

**Comment by etnbrd** [comment] 2015-11-26 14:19
Now that I updated to 2015-11-25, I don't have the error anymore.

Yes, I installed it from AMO (addons.mozill.org).

I think I could fix the problem in the css, but I don't know exactly how
firefox addons work.
What is the process to update the css, and reinstall the modified plugin ?

p.s. sorry, I answered by mail, and I didn't get your edit.

Thanks,

Etienne.

**Comment by skyschub** [comment] 2015-11-26 14:31
The height is updated via an event that gets triggered within the panel and send out of the content script back to the addon. This is not a CSS fix.

Could you try reproducing this issue with a clean profile? Instructions for creating a new profile is available at [support.mozilla.org](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles). If you cannot reproduce it, please head over to `about:support`, click "copy raw data to clipboard" and send me an email to mail@dennis-schubert.de. Maybe, I'll be able to reproduce your issue with the same addons and settings you have.

If you still have this issue in a clean profile, I have to try to reproduce it somehow, which could get a bit hard.

Instructions for getting a customized copy of this add-on running is available in this projects `README.md`.

**Comment by etnbrd** [comment] 2015-11-26 14:53
I cannot reproduce with a clean profile (It works).
I tried to disable all the addons, in my current profile, and it still
doesn't work.
I send the raw data to your mail.

Thanks,

Etienne.

**Comment by mnoorenberghe** [comment] 2016-03-08 01:41
> I tried to disable all the addons, in my current profile, and it still doesn't work.

@etnbrd Do you have the pref `nglayout.debug.disable_xul_cache` set to `true` in your regular profile? If so, see if that happens if you revert it to the default of false. It seems to break some UI. See [bug 1127744](https://bugzilla.mozilla.org/show_bug.cgi?id=1127744)

**Comment by etnbrd** [comment] 2016-03-10 15:50
Hi,

This pref doesn't appear in my config, so I guess it's not set.
Moreover, as the addon was broken on my config, I switch to the official
extension tabgroups.

**Comment by skyschub** [comment] 2016-03-10 15:51
I'm closing this since apparently, nobody else is able to reproduce this. :/

**Closed as completed by skyschub** 2016-03-10 15:51 UTC
Labels: needs confirmation
